
DROP SEQUENCE id_seq;
DROP TABLE ACCOUNT CASCADE;
DROP TABLE ACCOUNT_TRANSACTION CASCADE;
DROP TABLE STATEMENT_LINE_DETAIL CASCADE;
DROP TABLE ACCOUNT_ENTRY CASCADE;
DROP TABLE BUSINESS_TRANSACTION CASCADE;
DROP TABLE BUSINESS_TRANSACTION_DATA CASCADE;
DROP TABLE PROPOSED_TRANSACTION CASCADE;
DROP TABLE RESERVATION CASCADE;


-- Create sequence for id generation

CREATE SEQUENCE id_seq
  INCREMENT 100
  MINVALUE 101
  MAXVALUE 9223372036854775807
  START 101
  CACHE 1;

-- Create tables

CREATE TABLE ACCOUNT (
    ID INTEGER NOT NULL,
    CURRENT_BALANCE  DECIMAL(12,2) NOT NULL,
	RESERVED_AMOUNT  DECIMAL(12,2),
	CLIENT_NAME CHARACTER VARYING(255) NOT NULL,
	CLIENT_CODE CHARACTER VARYING(255) NOT NULL UNIQUE,
	ACCOUNT_TYPE CHARACTER VARYING(255) NOT NULL,
    LEDGER_ACCOUNT_TYPE CHARACTER VARYING(255) NULL,
	ACCOUNT_STATUS CHARACTER VARYING(255) NULL,
	CREATED_AT TIMESTAMP, 
	CREATED_BY CHARACTER VARYING(255),
	MODIFIED_AT TIMESTAMP,
	MODIFIED_BY CHARACTER VARYING(255),
	VERSION INTEGER DEFAULT 0
);

CREATE TABLE ACCOUNT_TRANSACTION (
    ID INTEGER NOT NULL,
    TRANSACTION_AMOUNT  DECIMAL(12,2) NOT NULL,
	TRANSACTION_TYPE  CHARACTER VARYING(255) NOT NULL,
	TRANSACTION_DATE  TIMESTAMP,
	TRANSACTION_STATUS CHARACTER VARYING(30),
	BUSINESS_TRANSACTION_ID INTEGER NOT NULL,
	CREATED_AT TIMESTAMP, 
	CREATED_BY CHARACTER VARYING(255),
	MODIFIED_AT TIMESTAMP,
	MODIFIED_BY CHARACTER VARYING(255),
	VERSION INTEGER DEFAULT 0
);

CREATE TABLE STATEMENT_LINE_DETAIL (
    ID INTEGER NOT NULL,
    ACCOUNT_ID INTEGER NOT NULL,
	BUSINESS_TRANSACTION_ID INTEGER NOT NULL,
    AVAILABLE_BALANCE DECIMAL(12,2) NOT NULL,
    CURRENT_BALANCE DECIMAL(12,2) NOT NULL,
	TRANSACTION_AMOUNT DECIMAL(12,2) NOT NULL,
	DESCRIPTION_CODE CHARACTER VARYING(100),
	TRANSACTION_DATE TIMESTAMP,
	TRANSACTION_TYPE CHARACTER VARYING(255) NOT NULL,
	STATUS CHARACTER VARYING(30),
	CREATED_AT TIMESTAMP, 
	CREATED_BY CHARACTER VARYING(255),
	MODIFIED_AT TIMESTAMP,
	MODIFIED_BY CHARACTER VARYING(255),
	VERSION INTEGER DEFAULT 0
) ;

CREATE TABLE ACCOUNT_ENTRY (
    ID INTEGER NOT NULL,
    ACCOUNT_ID  INTEGER NOT NULL,
    ACCOUNT_TRANSACTION_ID INTEGER NOT NULL, 
    AMOUNT DECIMAL(12,2) NOT NULL,
	ACCOUNT_ENTRY_TYPE CHARACTER VARYING(255) NOT NULL,
	CREATED_AT TIMESTAMP, 
	CREATED_BY CHARACTER VARYING(255),
	MODIFIED_AT TIMESTAMP,
	MODIFIED_BY CHARACTER VARYING(255),
	VERSION INTEGER DEFAULT 0
);
	
CREATE TABLE BUSINESS_TRANSACTION (
    ID INTEGER NOT NULL,
	BUSINESS_TRANSACTION_CODE  CHARACTER VARYING(255) NOT NULL,	
	STATUS CHARACTER VARYING(30),
	TRANSACTION_DATE TIMESTAMP,
	ACCOUNT_USER_CLIENT_CODE CHARACTER VARYING(255),
	CREATED_AT TIMESTAMP, 
	CREATED_BY CHARACTER VARYING(255),
	MODIFIED_AT TIMESTAMP,
	MODIFIED_BY CHARACTER VARYING(255),
	VERSION INTEGER DEFAULT 0
);
	
CREATE TABLE BUSINESS_TRANSACTION_DATA (
    ID INTEGER NOT NULL,
	BUSINESS_TRANSACTION_ID INTEGER NOT NULL,
	TRANS_DATA_KEY  CHARACTER VARYING(255),
    TRANS_DATA_VALUE  CHARACTER VARYING(250)
);

CREATE TABLE PROPOSED_TRANSACTION (
	ID INTEGER NOT NULL,
	BUSINESS_TRANSACTION_ID INTEGER NOT NULL,
	ACCOUNT_TRANSACTION_TYPE  CHARACTER VARYING(255) NOT NULL,
	ACCOUNT_TO_DEBIT  INTEGER NOT NULL,
	ACCOUNT_TO_CREDIT INTEGER NOT NULL,
	AMOUNT  DECIMAL(12,2) NOT NULL,
	TRANSACTION_DATE TIMESTAMP,
	STATUS CHARACTER VARYING(30),
	CREATED_AT TIMESTAMP, 
	CREATED_BY CHARACTER VARYING(255),
	MODIFIED_AT TIMESTAMP,
	MODIFIED_BY CHARACTER VARYING(255),
	VERSION INTEGER DEFAULT 0
);
	
CREATE TABLE RESERVATION (
	ID INTEGER NOT NULL,
	BUSINESS_TRANS_ID INTEGER NOT NULL,
	RESERVED_AMOUNT  DECIMAL(12,2) NOT NULL,
	INITIAL_RESERVATION DECIMAL(12,2) NOT NULL,
	ACCOUNT_ID  INTEGER NOT NULL,
	CREATED_AT TIMESTAMP, 
	CREATED_BY CHARACTER VARYING(255),
	MODIFIED_AT TIMESTAMP,
	MODIFIED_BY CHARACTER VARYING(255),
	VERSION INTEGER DEFAULT 0
);

-- Create table constraints

ALTER TABLE ACCOUNT
    ADD CONSTRAINT PK_ACCOUNT
    PRIMARY KEY (ID);
	
ALTER TABLE ACCOUNT_TRANSACTION
    ADD CONSTRAINT PK_ACCOUNT_TRANSACTION
    PRIMARY KEY (ID);
	
ALTER TABLE STATEMENT_LINE_DETAIL
    ADD CONSTRAINT PK_STATEMENT_LINE_DETAIL
    PRIMARY KEY (ID);
	
ALTER TABLE ACCOUNT_ENTRY
    ADD CONSTRAINT PK_ACCOUNT_ENTRY
    PRIMARY KEY (ID);
	
ALTER TABLE BUSINESS_TRANSACTION
    ADD CONSTRAINT PK_BUSINESS_TRANSACTION
    PRIMARY KEY (ID);

ALTER TABLE PROPOSED_TRANSACTION
    ADD CONSTRAINT PK_PROPOSED_TRANSACTION
    PRIMARY KEY (ID);

ALTER TABLE RESERVATION
    ADD CONSTRAINT PK_RESERVATION
    PRIMARY KEY (ID);

ALTER TABLE ACCOUNT_TRANSACTION 
    ADD CONSTRAINT FK_BUSINESS_TRANSACTION
    FOREIGN KEY (BUSINESS_TRANSACTION_ID) REFERENCES BUSINESS_TRANSACTION (ID);  

ALTER TABLE ACCOUNT_ENTRY 
    ADD CONSTRAINT FK_ACCOUNT_ENTRY
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID);

ALTER TABLE ACCOUNT_ENTRY 
    ADD CONSTRAINT FK_TRANSACTION_ID
    FOREIGN KEY (ACCOUNT_TRANSACTION_ID) REFERENCES ACCOUNT_TRANSACTION (ID);

ALTER TABLE BUSINESS_TRANSACTION_DATA ADD CONSTRAINT PK_BUSINESS_TRANSACTION_DATA 
	PRIMARY KEY (ID);
		
ALTER TABLE BUSINESS_TRANSACTION_DATA ADD CONSTRAINT FK_BUSINESS_TRANSACTION_DATA
	FOREIGN KEY (BUSINESS_TRANSACTION_ID) REFERENCES BUSINESS_TRANSACTION  (ID);	

	